version: 2
updates:
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '17:00'
      timezone: 'Africa/Johannesburg'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '17:00'
      timezone: 'Africa/Johannesburg'
